#
###################################
# Site wide configuration
####################################
#
title: Backward
email: MJRoche@mail.usf.edu
description: My backward approach to tech and code.
url: http://backward.herokuapp.com/


#
###################################
# Jekyll configuration
####################################
#
timezone:          America/New_York
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title
gems:
  - jemoji

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: #Matthew Roche
  avatar: backward-logo.png
  job: #"A lover of tech"
  bio: "A backward approach to tech and code."
  email: MJRoche@mail.usf.edu
  disqus-shortname: mjrocheblog
  twitter: 'MatthewJRoche'
  facebook: #username
  google:
    plus: #username
    analytics: UA-82350194-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: 'drawkcab'
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
